import Head from 'next/head'
import {useEffect, useState} from 'react'
import {Header} from "../components/Header";
import ContactItem from "../components/ContactItem";

export default function Home() {
    const [contacts, setContacts] = useState([]);

    const getLocalStorageData = () => {
        let data = JSON.parse(localStorage.getItem('contacts'))
        setContacts(() => {
            if (data && data.length > 0) {
                return data
            } else {
                return []
            }
        })
    }
    const setNewContacts = (newContacts) => {
        setContacts([
            ...contacts, newContacts
        ])
    }
    const removeContact = (id) => {
        setContacts(contacts.filter(obj => obj.id !== id))
    }
    const changeContact = ({name, number, id}) => {
        let copyState = [...contacts]
        let findСontact = contacts.find((obj) => obj.id === id)
        let deleteContact = copyState.filter(obj => obj.id !== id)
        setContacts([
            ...deleteContact, {...findСontact, name: name, number: number}
        ])
    }

    useEffect(() => {
        getLocalStorageData()
    }, [])
    useEffect(() => {
        localStorage.setItem('contacts', JSON.stringify(contacts))
    }, [contacts])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header setNewContacts={setNewContacts}/>
            <div className={'content'}>
                {contacts.length > 0 ? contacts.map((c, i) => <ContactItem removeContact={removeContact}
                                                     setNewContacts={setNewContacts}
                                                     key={i + c}
                                                     name={c.name}
                                                     changeContact={changeContact}
                                                     number={c.number}
                                                     id={c.id}/>)
                :<div className={'no-contacts'}>Нет контактов</div>}
            </div>
        </div>
    )
}
